openapi: 3.1.0
info:
  title: Installer API
  version: 1.0.0

servers:
  - url: https://api.example.com

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: SHA256

  schemas:
    ProvisionRequest:
      type: object
      properties:
        machineGuid:
          type: string
          example: "xxxx-xxxx"
      required:
        - machineGuid

    ProvisionResponse:
      type: object
      properties:
        deviceId:
          type: string
          example: "yyy"
        url:
          type: string
          format: uri
          example: "https://xx.x"

paths:
  /install/provision:
    post:
      summary: Validate license, register device, and get download URL
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProvisionRequest'
      responses:
        '200':
          description: Device registered and download URL returned successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProvisionResponse'
        '401':
          description: Unauthorized - invalid license key
